Schedule
cse-mosip/Exam-Attendance-UI pull request #64
Opened 2023-07-19 06:35 UTC by samadhi-k

![image](https://github.com/cse-mosip/Exam-Attendance-UI/assets/77055729/b54d2553-3651-4092-8d9c-560500f489fd)

2023-07-19 16:22 UTC, Malith-19 commented on src/pages/schedule-page.js
Let's  add the clickable option to the each row and it should navigate to the relevant exam monitoring page of that selected exam.

2023-07-19 16:26 UTC, Malith-19 commented on src/pages/schedule-page.js
Can we center the table footer which has showing the page number and other stuff.

2023-07-19 16:28 UTC, Malith-19 requested changes
Add some suggestions.

2023-07-19 16:28 UTC, Malith-19 commented
There are some conflicts with the main please check it too.

2023-07-20 08:09 UTC, samadhi-k commented
![image](https://github.com/cse-mosip/Exam-Attendance-UI/assets/77055729/4fd429dd-46d7-4fd6-928a-4967ea40a1ac)
Added the requested changes

2023-07-20 08:54 UTC, Malith-19 approved these changes

2023-07-20 13:55 UTC, merged